### ISSUE TITLE
Storybook 8 compatibility

### ISSUE THREAD

**Issue by joevaugh4n** [hwookim/storybook-addon-cookie#10]
Hey @hwookim ! I’m reaching out from the core SB team :)

Storybook 8 (our next major release) is coming soon, and it introduces some breaking changes that your addon might need to account for.

We’ve listed all the key changes in [a new Storybook 8 migration guide](https://storybook.js.org/docs/8.0/addons/addon-migration-guide#key-changes-for-addons), and we’d encourage you to check it out and see if your addon is impacted.

We also have an addons channel in our Discord community, which we’d like to use to better communicate with addon authors in the future. If you’re not part of the server, consider joining [here](https://discord.gg/wMff8FkF) and message me (@joevaugh4n) so that I can give you the addon creator role! If you’re already in the server, please just ping me and I’ll respond to you there.

Thanks for being a part of our addon community!

Joe

**Comment by sandwichsudo** [comment]
Hiya, I've just tried upgrading to Storybook 8 and have found my cookies are no longer set once I upgraded my Storybook to version 8 when using this add-on. I'll try and investigate a bit more what the breaking change might be and add notes here.

First off, this message comes out when I start my Storybook with version 8 installed:

>WARN The following packages are incompatible with Storybook 8.0.0 as they depend on different major versions of Storybook packages:
WARN - storybook-addon-cookie@3.2.0

**Comment by sandwichsudo** [comment]
I had a go at pulling the repo and upgrading those dependencies and then upgrading the demo Storybook to v8.0 and all seemed to work well, with the exception of the demo Storybook autogenerated docs page throwing a type error. Happy to push a PR if that's any help.

![Screenshot 2024-03-14 at 16 54 29](https://github.com/hwookim/storybook-addon-cookie/assets/4517593/e76ea960-d7e7-4965-bde9-3d8a4bd92d98)
![Screenshot 2024-03-14 at 16 54 41](https://github.com/hwookim/storybook-addon-cookie/assets/4517593/8ef59273-9778-4954-8ea5-2d1603b03167)
![Screenshot 2024-03-14 at 16 54 47](https://github.com/hwookim/storybook-addon-cookie/assets/4517593/177d5b25-6c97-4d83-9a08-4b1fc7df5020)
![Screenshot 2024-03-14 at 16 54 53](https://github.com/hwookim/storybook-addon-cookie/assets/4517593/b241ba25-056b-4944-a6a7-b6ae2cad39d3)
![Screenshot 2024-03-14 at 16 55 02](https://github.com/hwookim/storybook-addon-cookie/assets/4517593/22ec82f8-dc1f-44dc-9b75-49879891fbfc)
![Screenshot 2024-03-14 at 16 55 32](https://github.com/hwookim/storybook-addon-cookie/assets/4517593/c89b64a9-2024-425a-be63-a831a0f8cc51)

**Comment by sandwichsudo** [comment]
I had a go at upgrading:

-    "@storybook/blocks": "^7.0.0",
-    "@storybook/components": "^7.0.0",
-    "@storybook/manager-api": "^7.0.0",
-    "@storybook/preview-api": "^7.0.0",
-    "@storybook/types": "^7.0.0",
+    "@storybook/blocks": "^8.0.0",
+    "@storybook/components": "^8.0.0",
+    "@storybook/manager-api": "^8.0.0",
+    "@storybook/preview-api": "^8.0.0",
+    "@storybook/types": "^8.0.0",

and then the demo Storybook up to v8.0 and seemed to work well

![Screenshot 2024-03-14 at 17 05 29](https://github.com/hwookim/storybook-addon-cookie/assets/4517593/7e746c4d-3ad8-43bc-9087-576a95c16cf2)

Happy to push a PR if that's any help

**Comment by paul-asvb** [comment]
i threw this together. https://github.com/hwookim/storybook-addon-cookie/pull/11

**Comment by hwookim** [comment]
I apologize for the delay in handling this issue.
I'll do my best to get it taken care of this week.

**Comment by fernandopasik** [comment]
Thank you for the update! Is there anything in particular why the alpha release for 4.0 and not a full one?

**Comment by hwookim** [comment]
@fernandopasik 
There are a few issues we haven't resolved yet. #12  T.T
There is an issue with the parameter not being called properly on initial load and therefore not being properly exposed in the toolpane, which i'm still trying to resolve.

I'll try to resolve them as soon as possible!
