### ISSUE TITLE
| gets html encoded to %7C

### ISSUE THREAD

**Issue by thrownblown** [hwookim/storybook-addon-cookie#8]
In version 3.0.1 the cookie config below in Component.stories.tsx:

```
Primary.parameters = {
  // Set the viewports in Chromatic at a story level.
  layout: "fullscreen",
  chromatic: { viewports: [375, 834, 1200], delay: 3000 },
  cookie: {
    geo: "96094|WEED|CA|US",
  },
  mockData: [...
```  
  the cookie string in Storybook results:
```
document.cookie
'geo="96094|WEED|CA|US"'
```

in version 3.0.2:

```
document.cookie
'geo=96094%7CWEED%7CCA%7CUS'
```

**Comment by hwookim** [comment]
When writing and reading cookies, it is recommended to encode them via the `encodeURIComponent` function, so i updated that on `v3.0.2`.
I think it was a bad update to provide this in the library.

In version `v3.0.3`, I removed the logic around encoding.
Thanks for opening the issue.
